apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team02-prod"
  title: "simplenodeservice-team02-prod"
  description: "Template for the simplenodeservice owned and operated by team02 in environment prod"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team02-prod'
    argocd/app-name: simplenodeservice-team02-prod
  links:
    - url: https://github.com/fjghumphries/platform-engineering-demo.git
      title: Github Repo
      icon: github
    - url: https://special-space-funicular-xpx4w77jxg52v4v-80.app.github.dev/simplenodeservice-team02-prod
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://special-space-funicular-xpx4w77jxg52v4v-30100.app.github.dev/applications/argocd/simplenodeservice-team02-prod
    - title: View in Dynatrace
      icon: catalog
      url: https://enc67105.sprint.apps.dynatracelabs.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team02
  lifecycle: prod
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team02"
  description: Group for application team team02
spec:
  type: business-unit
  profile:
    displayName: Team 02
    email: team02@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
